# Generated by Django 4.2.4 on 2023-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_otclickofpost_likesofpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesofpost',
            name='bolean',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='otclickofpost',
            name='bolean',
            field=models.BooleanField(null=True),
        ),
    ]
