# Generated by Django 4.2.4 on 2023-08-25 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_customuser_phone_ownanimal_animalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownanimal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_animals', to=settings.AUTH_USER_MODEL),
        ),
    ]
