# Generated by Django 4.2.4 on 2023-08-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_ownanimal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='post_take_animal',
            new_name='animal',
        ),
    ]
