# Generated by Django 4.2.4 on 2023-08-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_likesofanimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likesofanimal',
            old_name='post',
            new_name='animal',
        ),
    ]
