# Generated by Django 4.2.4 on 2023-08-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_post_likesofanimal_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownanimal',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
