# Generated by Django 4.2.4 on 2023-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_ownanimal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownanimal',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
