# Generated by Django 4.2.4 on 2023-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_animalimage_image_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.ImageField(blank=True, default='animals_images/default.png', null=True, upload_to='animals_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='animals_images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, default='animals_images/default.png', null=True, upload_to='animals_images/'),
        ),
        migrations.AlterField(
            model_name='ownanimal',
            name='image',
            field=models.ImageField(blank=True, default='animals_images/default.png', null=True, upload_to='animals_images/'),
        ),
        migrations.AlterField(
            model_name='takeanimalimage',
            name='image',
            field=models.ImageField(blank=True, default='animals_images/default.png', null=True, upload_to='animals_images/'),
        ),
    ]
