# Generated by Django 4.2.4 on 2023-08-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_likesofanimalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforownanimal',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
